workflows:
  ios-development:
    name: iOS Development Build
    environment:
      vars:
        BUNDLE_ID: "com.example.zapItMobile"
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        certificates:
          - Zap It
        provisioning_profiles:
          - Zap it Development
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: pod install --project-directory=ios
      - name: Build Flutter iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Extract signing info
        script: |
          PROFILE_PATH=$(find "$HOME/Library/MobileDevice/Provisioning Profiles" -name "*.mobileprovision" | head -1)
          TEAM_ID=$(security cms -D -i "$PROFILE_PATH" | plutil -extract TeamIdentifier.0 raw -)
          CERT_NAME=$(security find-identity -v -p codesigning | grep "Apple Development" | head -1 | sed 's/.*"\(.*\)"/\1/')
          echo "export DEVELOPMENT_TEAM=\"$TEAM_ID\"" >> $CM_ENV
          echo "export CODE_SIGN_IDENTITY=\"$CERT_NAME\"" >> $CM_ENV
          echo "export PROFILE_NAME=\"Zap it Development\"" >> $CM_ENV
      - name: Archive with xcodebuild (manual signing)
        script: |
          cd ios
          xcodebuild clean -project Runner.xcodeproj -scheme Runner -configuration Release
          xcodebuild archive \
            -project Runner.xcodeproj \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/ios/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"
      - name: Export IPA
        script: |
          cd ios
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF
          mkdir -p ../build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath ../build/ios/Runner.xcarchive \
            -exportPath ../build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
