# Codemagic CI/CD Configuration
# 
# iOS Workflows:
# - ios-development: For testing IPA builds without code signing (use this first)
# - ios-workflow: For simulator builds (no code signing required)
# 
# Note: For device builds and App Store deployment, you'll need:
# 1. Apple Developer Account
# 2. Code signing certificates
# 3. Provisioning profiles
# 4. App Store Connect API credentials
# 
# Android Workflows:
# - android-workflow: For Android APK and App Bundle builds
# 
# Web Workflows:
# - web-workflow: For web builds

workflows:
  ios-development:
    name: iOS Development Build
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.zapItMobile"
        FLUTTER_VERSION: "stable"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build ipa for development
        script: |
          flutter build ipa --debug \
            --target=lib/main_debug.dart
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log

  ios-workflow:
    name: iOS Simulator Build
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.zapItMobile"
        FLUTTER_VERSION: "stable"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build for iOS simulator
        script: |
          flutter build ios --debug \
            --target=lib/main_debug.dart \
            --simulator
      - name: Create simulator build archive
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -derivedDataPath build \
            build
    artifacts:
      - ios/build/**/*.app
      - flutter_drive.log

  android-workflow:
    name: Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.zap_it_mobile"
        FLUTTER_VERSION: "stable"
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Set up code signing settings
        script: |
          echo $CM_KEYSTORE_PATH | base64 --decode > /tmp/keystore.keystore
          cd android
          echo "storeFile=/tmp/keystore.keystore" >> key.properties
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> key.properties
      - name: Verify Google Services
        script: |
          echo "=== Verifying google-services.json files ==="
          ls -la android/app/google-services.json
          ls -la android/app/src/main/google-services.json
          ls -la android/app/src/debug/google-services.json
          ls -la android/app/src/release/google-services.json
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build apk
        script: flutter build apk --release --target=lib/main_prod.dart
      - name: Flutter build appbundle
        script: flutter build appbundle --release --target=lib/main_prod.dart
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - /tmp/bitrise_upload_dir/*.aab
      - flutter_drive.log
    # publishing:
    #   google_play:
    #     track: internal
    #     submit_as_draft: true
    #     credentials: $GOOGLE_PLAY_CREDENTIALS

  web-workflow:
    name: Web Build
    environment:
      vars:
        FLUTTER_VERSION: "stable"
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build web
        script: flutter build web --release --target=lib/main_prod.dart
    artifacts:
      - build/web/**
      - flutter_drive.log 