workflows:
  ios-development:
    name: iOS Development Build
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.zapItMobile"
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        certificates:
          - Zap It
        provisioning_profiles:
          - Zap it Development
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: pod install --project-directory=ios
      - name: Debug code signing setup
        script: |
          echo "=== Debugging code signing ==="
          echo "Available certificates:"
          security find-identity -v -p codesigning
          echo ""
          echo "Available provisioning profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          echo ""
          echo "Checking project settings:"
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | grep -E "(CODE_SIGN|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|PROVISIONING_PROFILE)"
      - name: Apply Development profiles
        script: |
          echo "Applying Development profiles"
          xcode-project use-profiles --archive-method=development --code-signing-setup-verbose-logging
      - name: Try Flutter build first
        script: |
          echo "Trying Flutter build approach (Debug for Development)"
          flutter build ipa --debug --verbose || echo "Flutter build failed, continuing with Xcode"
      - name: Build IPA Development
        script: |
          echo "Building Development IPA with Xcode"
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME" --verbose
      - name: Verify IPA
        script: |
          echo "Checking for IPA files"
          find build/ios -name "*.ipa" -type f || true
          ls -la build/ios/ipa/ || echo "IPA directory not found"
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log

  ios-release:
    name: iOS Release Build  
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.zapItMobile"
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        certificates:
          - Zap It
        provisioning_profiles:
          - Zap it Development
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: pod install --project-directory=ios
      - name: Apply Development profiles
        script: |
          echo "Applying Development profiles"
          xcode-project use-profiles --archive-method=development --code-signing-setup-verbose-logging
      - name: Try Flutter build first
        script: |
          echo "Trying Flutter build approach (Release)"
          flutter build ipa --release --verbose || echo "Flutter build failed, continuing with Xcode"
      - name: Build IPA Release
        script: |
          echo "Building Release IPA with Xcode"
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME" --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
