workflows:
  ios-development:
    name: iOS Development Build
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.zapItMobile"
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        certificates:
          - dev_cert_reference
        provisioning_profiles:
          - dev_profile_reference
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: pod install --project-directory=ios
      - name: Apply Development profiles
        script: |
          echo "Applying Development profiles…"
          xcode-project use-profiles --archive-method=development --code-signing-setup-verbose-logging
      - name: Build IPA (Development)
        script: |
          echo "Building Development IPA…"
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
      - name: Verify IPA
        script: |
          echo "=== Checking for IPA files ==="
          find build/ios -name "*.ipa" -type f || true
          ls -la build/ios/ipa/ || echo "IPA directory not found"
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log

  ios-adhoc:
    name: iOS Device Build (Ad Hoc)
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.
